# Generated by Django 5.2.4 on 2025-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumematcher',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
