# Generated by Django 5.2.4 on 2025-07-04 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_resumematcher_resume_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumematcher',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
